project_id = "ojovgionwaywaaddczwl"

[functions.mock-transcribe]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.extract-topics]
verify_jwt = false